# Generated by Django 2.1.5 on 2019-03-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
