# Generated by Django 2.1.5 on 2019-03-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0002_auto_20190322_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='org_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
