# Generated by Django 2.1.5 on 2019-03-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0003_users_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
