# Generated by Django 2.1.5 on 2019-03-22 07:33

import datetime
from django.db import migrations, models
import hoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0004_remove_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('tenderID', models.CharField(default=hoo.models.tender.pkgen, max_length=25, primary_key=True, serialize=False)),
                ('organization_chain', models.CharField(max_length=30)),
                ('emd_amount', models.PositiveIntegerField()),
                ('emd_patable_to', models.TextField()),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('bid_end_date', models.DateTimeField()),
                ('document_name', models.CharField(max_length=20)),
                ('document_description', models.TextField()),
                ('details', models.TextField()),
                ('is_display', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='hoo.topping'),
        ),
    ]
