# Generated by Django 2.1.5 on 2019-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0006_auto_20190322_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='organization_chain',
            field=models.CharField(max_length=100),
        ),
    ]
