# Generated by Django 2.1.5 on 2019-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0007_auto_20190322_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(choices=[('G', 'GOODS'), ('S', 'SERVICES'), ('W', 'WORKS')], default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tender',
            name='product_category',
            field=models.CharField(choices=[('1', 'Civil Works'), ('2', 'Advertisement Services'), ('3', 'Computer Works'), ('4', 'Electrical Works'), ('5', 'Food')], default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='tender',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
