# Generated by Django 2.1.5 on 2019-03-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0008_auto_20190322_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=20)),
                ('tenderID', models.CharField(max_length=25)),
                ('is_liked', models.BooleanField(default=True)),
            ],
        ),
    ]
