# Generated by Django 2.1.5 on 2019-04-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0010_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='fileupload',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
