# Generated by Django 2.1.5 on 2019-04-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0011_auto_20190405_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='fileupload',
        ),
    ]
