# Generated by Django 2.1.5 on 2019-04-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0013_bids_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='from_userID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='tenderID',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
