# Generated by Django 2.1.5 on 2019-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0014_auto_20190405_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='detail',
            field=models.TextField(default='None'),
        ),
    ]
