# Generated by Django 2.1.5 on 2019-04-07 08:19

from django.db import migrations, models
import hoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0015_bids_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='tran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transID', models.CharField(default=hoo.models.tran.pkgen, max_length=16)),
                ('to_userID', models.CharField(max_length=20)),
                ('bid_id', models.IntegerField()),
                ('tenderID', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('timestamp', models.CharField(default=hoo.models.tran.get_ts, max_length=30)),
            ],
        ),
    ]
