# Generated by Django 2.1.5 on 2019-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0016_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
