# Generated by Django 2.1.5 on 2019-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoo', '0017_tender_is_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_userID', models.IntegerField()),
                ('notification', models.CharField(default='None', max_length=100)),
                ('pushed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='noti',
            field=models.IntegerField(default=-1),
        ),
    ]
